#! /usr/bin/perl

use Vpostmail;
use strict;

my $domain = $ARGV[0];

if ($domain eq ''){
	print usage();
	exit 1;
}

my $d = Vpostmail->new();
$d->setDomain($domain);
if($d->domainExists()){
	print STDERR "Domain $domain already configured\n";
	exit 1;
}
$d->createDomain();

exit;

sub usage{

return <<EOF;
vadddomain

Adds a domain to the mail system. 

Usage:

  vadddomain <domain>

Returns 0 on success, 1 on any sort of failure
EOF
}
