#! /usr/bin/perl

use Vpostmail;
use strict;
use Getopt::Std;

my %opt;
my $user = pop;
getopts('h', \%opt);

if ($user eq '' || $user eq '-h' || exists($opt{h})){
        print usage();
        exit 1;
}

print "Handy warning: I can't even find mailboxes yet, let alone delete them :)\n";

my $d = Vpostmail->new();

$d->setUser($user);
if ($d->userExists){
	if($d->userIsAlias){
		$d->removeAliasUser();
	}else{
		$d->removeUser();
	}
}else{
	print STDERR "User $user doesn't exist\n";
	exit 1;
}

if($d->userExists){
	print STDERR "Something's up. I tried to delete the user but it's still there.\n";
	exit 1;
}


sub usage{
return <<EOF;
vdeluser

Removes a user from the system

Usage:

vdeluser [options] <user>

Cannot delete mailboxes, though.

EOF
}
