#! /usr/bin/perl

use strict;
use Vpostmail;
use Getopt::Std;
my %opt;
getopts('h', \%opt);

if(exists($opt{h})){
	print usage();
	exit 0;
}

my $d = Vpostmail->new();

my $domain = $ARGV[0];
if ($domain eq ''){
	foreach($d->listDomains){
		print "$_\n";
	}
	exit 0;
}

my %info;
$d->setDomain($domain);
if ($d->domainExists){
	%info = $d->getDomainInfo();
}else{
	print STDERR "Domain $domain not found\n";
	exit 1;
}

foreach(sort(keys(%info))){
	unless($_ =~ /^mailboxes$/){
		printf('%-14s%s', $_, $info{$_});
		print "\n";
	}
}

sub usage{
return <<EOF;
vdominfo

Usage: 
  vdominfo <domain>

Prints out info on a domain. No analogy with vpopmail's
vdominfo is attempted.

EOF
}
