#! /usr/bin/perl

use strict;
use Vpostmail;
use Getopt::Std;
my %opt;
my $domain = pop;
getopts('lh', \%opt);

if(exists($opt{h})){
	print usage();
	exit 0;
}

my $d = Vpostmail->new();

if ($domain eq ''){
	foreach($d->listDomains){
		$d->setDomain($_);
		if ($d->domainIsAlias){
			my $target = ($d->getDomainAliasTarget);
			print "$_\t(alias for $target)\n";
		}else{
			print "$_\n";
		}
	}
	exit 0;
}

my %info;
$d->setDomain($domain);
if ($d->domainExists){
	if ($d->domainIsAlias){
		$d->setDomain($d->getDomainAliasTarget);
	}
	if(exists($opt{l})){
		foreach($d->listUsers){
			print $_."\n";
		}
	}else{
		%info = $d->getDomainInfo();
		foreach(sort(keys(%info))){
			unless($_ =~ /^mailboxes$/){
				printf('%-14s%s', $_, $info{$_});
				print "\n";
			}
		}
	}
}else{
	print STDERR "Domain $domain not found\n";
	exit 1;
}


sub usage{
return <<EOF;
vdominfo

Usage: 
  vdominfo [options[ <domain>

Prints out info on a domain. No analogy with vpopmail's
vdominfo is attempted.

Options:
  -l   print a list of mailboxes rather than domain properties

EOF
}
